name: Publish to NuGet
on:
  push:
    tags:
    - nuget*
  
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: 6.0.x
      - run: dotnet clean
      - name: 'Restore packages'
        run: dotnet restore CMouss.NFTTools/CMouss.NFTTools.csproj
      - name: 'Build project'
        run: dotnet build CMouss.NFTTools/CMouss.NFTTools.csproj --no-restore
      
      - name: 'Pack project'
        run: dotnet pack CMouss.NFTTools/CMouss.NFTTools.csproj --no-restore --no-build --configuration Debug --output output

      - name: "Push package"
        run: dotnet nuget push output\*.nupkg -k ${{ secrets.NUGETKEY }} -s https://api.nuget.org/v3/index.json